name: Repo Auto Sync

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 3 点执行（北京时间早上 11 点）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub

      - name: Sync all repositories once
        if: github.event_name == 'workflow_dispatch'  # 仅手动触发时运行
        run: |
          python sync_repos.py

      - name: Sync 30 repositories daily
        if: github.event_name == 'schedule'  # 每天定时触发时运行
        run: |
          python sync_some_repos.py
