# .github/workflows/sync.yml

name: Repo Auto Sync

on:
  workflow_dispatch:  # 支持手动触发
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 3 点执行（北京时间早上 11 点）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub

      - name: Sync Repositories
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          python sync_repos.py

      - name: Commit Updated Markdown
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git pull
          git add repos_sync_list.md
          git commit -m "Update sync status" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
